name: Notify Discord of new release
on:
  release:
    types: [released]
    # types: [published, released, created, edited]
  workflow_dispatch:
jobs:
  publish_discord_message:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: "Setup JS dependencies"
        uses: ./.github/actions/setup-project

      - name: "Send Discord message"
        id: discord-notify-release
        uses: ./.github/actions/notify-release
        with:
          discord_webhook_url: ${{ secrets.RELEASES_DISCORD_WEBHOOK }}
